---
title: Site name
lang: pt-BR
base_url: /fatec-notes/
pagefind: true
topnav:
  links:
    - text: Link 1
      href: https://example.com/link-1
    - text: Link 2
      href: https://example.com/link-2
